// Auto-generated by assemble.ts — do not edit manually
import type { ReelProps } from "../types";

export const generatedReelProps: ReelProps & { narrationSrc: string; musicSrc?: string } = {
  "clips": [
    {
      "src": "generated/gen-avatar-0.mp4",
      "durationInFrames": 110,
      "videoDurationInFrames": 110,
      "sceneType": "avatar"
    },
    {
      "src": "generated/gen-broll-0.mp4",
      "durationInFrames": 106,
      "videoDurationInFrames": 106,
      "sceneType": "broll"
    },
    {
      "src": "generated/gen-avatar-1.mp4",
      "durationInFrames": 81,
      "videoDurationInFrames": 81,
      "sceneType": "avatar"
    }
  ],
  "captions": [
    {
      "text": "Imagine losing revenue every hour",
      "startFrame": 0,
      "endFrame": 57,
      "position": "bottom-center",
      "animation": "pop",
      "fontSize": 64,
      "color": "#FFFFFF"
    },
    {
      "text": "because your charger is offline.",
      "startFrame": 58,
      "endFrame": 113,
      "position": "bottom-center",
      "animation": "pop",
      "fontSize": 64,
      "color": "#FFFFFF"
    },
    {
      "text": "Go2EV monitors every station in real time.",
      "startFrame": 122,
      "endFrame": 209,
      "position": "bottom-center",
      "animation": "pop",
      "fontSize": 64,
      "color": "#FFFFFF"
    },
    {
      "text": "Try it free at go2ev.com.",
      "startFrame": 216,
      "endFrame": 300,
      "position": "bottom-center",
      "animation": "pop",
      "fontSize": 64,
      "color": "#FFFFFF"
    }
  ],
  "captionStyle": "bold-pop",
  "branding": {
    "logo": "logo.svg",
    "website": "go2ev.com"
  },
  "fps": 30,
  "durationInFrames": 297,
  "sceneOverlays": [],
  "narrationSrc": "generated/narration.mp3",
  "musicSrc": "generated/music.mp3"
};
